# Generated by Django 3.2.9 on 2021-12-23 14:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0028_auto_20211223_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('realted_disciplines', models.ManyToManyField(blank=True, to='blog.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('related_disciplines', models.ManyToManyField(blank=True, to='blog.Discipline')),
                ('related_subjects', models.ManyToManyField(blank=True, to='question.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(max_length=200)),
                ('related_subject', models.ManyToManyField(blank=True, to='question.Subject')),
                ('topic', models.ManyToManyField(blank=True, to='question.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('correct_choice', models.IntegerField()),
                ('solution', ckeditor.fields.RichTextField()),
                ('video_solution_url', models.CharField(blank=True, max_length=1000)),
                ('subject', models.ManyToManyField(blank=True, to='question.Subject')),
                ('subtopic', models.ManyToManyField(blank=True, to='question.SubTopic')),
                ('topic', models.ManyToManyField(blank=True, to='question.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='MemberSolvedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solving_time', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCompletedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completing_time', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.member')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.topic')),
            ],
        ),
    ]
