# Generated by Django 3.2.9 on 2021-12-23 17:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='realted_disciplines',
            new_name='related_disciplines',
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
