# Generated by Django 3.2.9 on 2021-12-24 17:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20211223_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='related_theory',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='related_theory',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
