# Generated by Django 3.2.9 on 2021-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20211224_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='topic',
            name='related_image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
