# Generated by Django 3.2.9 on 2021-12-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20211229_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='related_image',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
