# Generated by Django 3.2.9 on 2021-12-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_topic_related_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='related_image',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
