# Generated by Django 3.2.9 on 2021-12-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20211229_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
