# Generated by Django 3.2.9 on 2021-12-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20211229_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
