# Generated by Django 3.2.9 on 2021-12-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_subject_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='url',
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='related_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='related_image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
