# Generated by Django 3.2.9 on 2021-12-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_auto_20211230_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='solution_image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
