# Generated by Django 3.2.9 on 2021-12-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_remove_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersolvedquestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
