# Generated by Django 3.2.9 on 2021-12-30 15:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_auto_20211230_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('question_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('option_a', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('option_b', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('option_c', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('option_d', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('correct_choice', models.IntegerField()),
                ('solution', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('solution_image', models.URLField(blank=True, default='')),
                ('video_solution_url', models.CharField(blank=True, max_length=1000)),
                ('slug', models.SlugField(blank=True, default='')),
                ('subject', models.ManyToManyField(blank=True, to='question.Subject')),
                ('subtopic', models.ManyToManyField(blank=True, to='question.SubTopic')),
                ('topic', models.ManyToManyField(blank=True, to='question.Topic')),
            ],
        ),
        migrations.DeleteModel(
            name='MemberSolvedQuestion',
        ),
    ]
