# Generated by Django 3.2.9 on 2021-12-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_membersolvedquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
