# Generated by Django 3.2.9 on 2021-12-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0024_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
