# Generated by Django 3.2.9 on 2022-01-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0025_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
