# Generated by Django 2.2.13 on 2021-11-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qnum', models.CharField(max_length=100)),
                ('Qtext', models.TextField()),
            ],
        ),
    ]
