# Generated by Django 3.2.9 on 2021-12-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_question_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_subjects',
        ),
        migrations.AddField(
            model_name='topic',
            name='related_subjects',
            field=models.ManyToManyField(blank=True, to='blog.Subject'),
        ),
    ]
