# Generated by Django 3.2.9 on 2021-12-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211216_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(blank=True, to='blog.Topic'),
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(max_length=200)),
                ('subject', models.ManyToManyField(blank=True, to='blog.Subject')),
                ('topic', models.ManyToManyField(blank=True, to='blog.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ManyToManyField(blank=True, to='blog.SubTopic'),
        ),
    ]
