# Generated by Django 3.2.9 on 2021-12-16 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20211216_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='order_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.orderdetail'),
        ),
    ]
