# Generated by Django 3.2.9 on 2021-12-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_member_order_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
