# Generated by Django 3.2.9 on 2021-12-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='subject',
            new_name='related_subject',
        ),
        migrations.AddField(
            model_name='member',
            name='appearing_year',
            field=models.CharField(blank=True, choices=[('THIS YEAR', 'THIS YEAR'), ('NEXT YEAR', 'NEXT YEAR'), ('NEXT TO NEXT YEAR', 'NEXT TO NEXT YEAR'), ('NOT PLANNING TO GIVE FE EXAMS', 'NOT PLANNING TO GIVE FE EXAMS')], max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='realted_disciplines',
            field=models.ManyToManyField(blank=True, to='blog.Discipline'),
        ),
        migrations.AddField(
            model_name='topic',
            name='related_disciplines',
            field=models.ManyToManyField(blank=True, to='blog.Discipline'),
        ),
    ]
