# Generated by Django 3.2.9 on 2021-12-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_membercompletedtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThoughtData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought_data', models.CharField(max_length=800)),
                ('author', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
